development:
  facebook_key: <%= ENV["facebook_key"] %>
  facebook_secret: <%= ENV['facebook_secret'] %>

  twitter_key: "Enter your keys here. Check Read me file to know how to get keys"
  twitter_secret: "Enter your keys here. Check Read me file to know how to get keys"

  github_key: "Enter your keys here. Check Read me file to know how to get keys"
  github_secret: "Enter your keys here. Check Read me file to know how to get keys"

  linkedin_key: "Enter your keys here. Check Read me file to know how to get keys"
  linkedin_secret: "Enter your keys here. Check Read me file to know how to get keys"

  google_key: <%= ENV['google_key'] %>
  google_secret: <%= ENV['google_secret'] %>

test:
  facebook_key: <%= ENV['facebook_key'] %>
  facebook_secret: <%= ENV['facebook_secret'] %>

  twitter_key: "Enter your keys here. Check Read me file to know how to get keys"
  twitter_secret: "Enter your keys here. Check Read me file to know how to get keys"

  github_key: "Enter your keys here. Check Read me file to know how to get keys"
  github_secret: "Enter your keys here. Check Read me file to know how to get keys"

  linkedin_key: "Enter your keys here. Check Read me file to know how to get keys"
  linkedin_secret: "Enter your keys here. Check Read me file to know how to get keys"

  google_key: <%= ENV['google_key'] %>
  google_secret: <%= ENV['google_secret'] %>

production:
  facebook_key: <%= ENV["facebook_key"] %>
  facebook_secret: <%= ENV['facebook_secret'] %>

  twitter_key: "Enter your keys here. Check Read me file to know how to get keys"
  twitter_secret: "Enter your keys here. Check Read me file to know how to get keys"

  github_key: "Enter your keys here. Check Read me file to know how to get keys"
  github_secret: "Enter your keys here. Check Read me file to know how to get keys"

  linkedin_key: "Enter your keys here. Check Read me file to know how to get keys"
  linkedin_secret: "Enter your keys here. Check Read me file to know how to get keys"

  google_key: <%= ENV['google_key'] %>
  google_secret: <%= ENV['google_secret'] %>
